### ISSUE TITLE
[BUG] Using both GenericToken.Double and GenericToken.Int together causes double tokens to have their IsEOS flag set to true

### ISSUE THREAD

**Issue by Techcraft7** [b3b00/csly#218] opened 2020-12-25 03:50 UTC
# Description

So in my project 7Sharp, I use both `GenericToken.Double` and `GenericToken.Int` as tokens in my interpreter. 

However, double tokens appear to be an `<<EOS>>` even though the tokens value's (`TokenID`, `DoubleValue`) are set properly.

## Visual

![image](https://user-images.githubusercontent.com/35858721/103117806-2784e380-463a-11eb-8330-7db82fead8ef.png)
##### Becomes
![image](https://user-images.githubusercontent.com/35858721/103117799-205dd580-463a-11eb-9301-3aad8f545632.png)

### Source code: [7Sharp repo](https://github.com/Techcraft7/7Sharp/tree/master/7Sharp)

Files you may be interested in:
- TokenType.cs
- Interpreter.cs
- Utils.cs

Edit: I'm currently testing with a Fibonacci program. Mind my bad notepad++ custom style.
![image](https://user-images.githubusercontent.com/35858721/103117882-82b6d600-463a-11eb-8a4b-fdc7fd36fc16.png)

**Comment by Techcraft7** [comment] 2020-12-25 03:58
I was looking though the code, and I found [this](https://github.com/b3b00/csly/blob/e8b23131e1657ba43d0f5ff6e33fe114653ed5b9/sly/lexer/GenericLexer.cs#L261)

Not sure if its part of the issue but it appears to me that the `GeneicLexer` doesn't account for using BOTH `Int` and `Double` generic tokens. Not sure, but I'd like to hear what you guys might have to say about that

**Comment by b3b00** [comment] 2020-12-31 09:22
I will look at it soon, but right now it's december the 31and I have some night to prepare :)

**Comment by b3b00** [comment] 2020-12-31 09:49
I push a branch bugfix/issue218 whre you can find my fix proposal in IssuesTests.cs => Token218 enum : 
https://github.com/b3b00/csly/blob/bugfix/issue218/ParserTests/IssuesTests.cs

**Comment by b3b00** [comment] 2020-12-31 12:44
Reading my code I think the problem is only a display issue in the Token.ToString() method.

**Comment by b3b00** [comment] 2021-01-01 08:25
Indeed it was merely a display bug. I have fixed on dev branch. No release planned soon but you may not need it as all Token object attributes are correctly set.
Reading your code I saw that you do not use the CSLY parser but rather choose an hand made parser. Did you try CSLY parser and find it does not match your needs ? if so will be interesting for me to know why to improve it as much as I can.

Thank you for your issue report.

**Closed by b3b00** 2021-01-01 08:25 UTC

**Comment by Techcraft7** [comment] 2021-01-09 22:35
Thanks!
